version: '3'

#Docker Networks
networks:
  privateLan:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/24

services:
  #Laravel App
  app:
    env_file: ./src/.env
    build:
      context: .
      dockerfile: deploy/Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html:cached
    networks:
      privateLan:
        ipv4_address: 172.10.0.2

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "9053:80"
    volumes:
      - ./src:/var/www/html:cached
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      privateLan:
        ipv4_address: 172.10.0.3

  #MySQL Service
  db:
    image: mariadb:10.6-focal
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "app_db"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "123456"
      MYSQL_ROOT_PASSWORD: "SuperSecret"
    volumes:
      - ./dbdata:/var/lib/mysql/
    networks:
      privateLan:
        ipv4_address: 172.10.0.5
