version: '3'

#Docker Networks
networks:
  lan:
    driver: bridge

services:
  #Laravel App
  app:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    image: prophet
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./prophet:/var/www/html:cached
    networks:
      - lan

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "9053:80"
    volumes:
      - ./prophet:/var/www/html:cached
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - lan

  #MySQL Service
  db:
    image: mariadb:10.6-focal
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "prophet"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "123456"
      MYSQL_ROOT_PASSWORD: "SuperSecret"
    volumes:
      - ./dbdata:/var/lib/mysql/
    networks:
      - lan
